language: node_js
node_js:
  - "10"
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli

jobs:
  include:
    - stage: lint
      script: - ng lint
    - stage: build
      script: - ng build --prod --base-href https://github.com/wwalkley/recipe-book
